name: sams
description: "A new Flutter project."

publish_to: "none"

version: 1.4.0+4

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  connectivity_plus: ^6.0.2
  context_storage: ^1.0.0+1
  cupertino_icons: ^1.0.2
  file_picker: ^6.2.0
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  get: ^4.6.6
  google_sign_in: ^6.2.1
  http: ^1.2.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  open_store: ^0.5.0
  page_transition: ^2.1.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#EFAE7D"
  image_path: "assets/png/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/png/
    - assets/svg/
    - assets/jpg/
    - assets/fonts/
  fonts:
    - family: Serif
      fonts:
        - asset: assets/fonts/IBMPlexSerif-Medium.ttf
    - family: Poppin
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_slnt,wght.ttf
